name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ["ubuntu-22.04"]

    strategy:
      matrix:
        go_version: ["1.21", stable]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
      - run: make
