name: coverage

on:
  push:
    paths:
      - "**/*.go"
  pull_request:
    paths:
      - "**/*.go"

jobs:
  coverage:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make coverage
      - uses: codecov/codecov-action@v4.0.1
        with:
          files: ./build/redlog.coverage ./build/pkgs.coverage
          token: ${{ secrets.CODECOV_TOKEN }}
