on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          include-component-in-tag: true
